# Generated by Django 2.2.5 on 2019-09-14 08:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_updateagain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UpdateAgain',
        ),
        migrations.AddField(
            model_name='update',
            name='title',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
